"""
TTNN MoE for GraniteMoeHybrid - expert-parallel sharding across mesh devices.
"""

import torch
import ttnn

from utils.device import _is_mesh_device


class GraniteTTMoE:
    """Expert-parallel Mixture-of-Experts for Granite on TTNN."""

    def __init__(
        self,
        hf_moe,
        device,
        weight_dtype=ttnn.bfloat8_b,
        act_dtype=ttnn.bfloat16,
        use_all_gather=True,
        tt_ccl=None,
    ):
        self.hf_moe = hf_moe
        self.device = device
        self.dtype = weight_dtype
        self.act_dtype = act_dtype
        self.tt_ccl = tt_ccl

        self.is_mesh = _is_mesh_device(device)
        self.num_devices = device.get_num_devices() if self.is_mesh else 1

        self._topology = ttnn.Topology.Linear

        self.num_experts = hf_moe.input_linear.num_experts
        self.hidden_size = hf_moe.input_size
        self.intermediate_size = hf_moe.hidden_size
        self.top_k = hf_moe.router.top_k

        if self.is_mesh and self.num_devices > 1:
            mesh_shape = device.shape
            self._mesh_rows = mesh_shape[0]
            self._mesh_cols = mesh_shape[1]
        else:
            self._mesh_rows = 1
            self._mesh_cols = 1

        # Determine if we can use column-parallel or multi-row expert parallelism.
        self._use_col_parallel = (
            (self._mesh_rows == 1) and self.num_devices > 1 and use_all_gather
        )
        self._is_multirow = (
            (self._mesh_rows > 1) and self.num_devices > 1 and use_all_gather
        )

        if self._use_col_parallel:
            effective_cols = self._mesh_cols
            while effective_cols > 1 and self.num_experts % effective_cols != 0:
                effective_cols -= 1
            self.effective_cols = effective_cols
            self.effective_devs = effective_cols
            self.experts_per_device = self.num_experts // effective_cols
            self._ep_mapper = (
                ttnn.ShardTensor2dMesh(
                    self.device,
                    dims=(None, 1),
                    mesh_shape=ttnn.MeshShape(1, effective_cols),
                )
                if effective_cols > 1
                else (ttnn.ReplicateTensorToMesh(self.device) if self.is_mesh else None)
            )
        elif self._is_multirow:
            effective_rows = self._mesh_rows
            while effective_rows > 1 and self.num_experts % effective_rows != 0:
                effective_rows -= 1
            self.effective_cols = effective_rows
            self.effective_devs = effective_rows
            self.experts_per_device = self.num_experts // effective_rows
            self._ep_mapper = (
                ttnn.ShardTensor2dMesh(
                    self.device,
                    dims=(1, None),
                    mesh_shape=device.shape,
                )
                if effective_rows > 1
                else (ttnn.ReplicateTensorToMesh(self.device) if self.is_mesh else None)
            )
        else:
            self.effective_cols = 1
            self.effective_devs = 1
            self.experts_per_device = self.num_experts
            self._ep_mapper = (
                ttnn.ReplicateTensorToMesh(self.device) if self.is_mesh else None
            )

        self._load_weights()
        self._load_router_weight()

    def _load_router_weight(self):
        """Upload router weight and routing identity matrices to device.

        router_weight_tt: learned [hidden_size, num_experts] weight that scores each expert.
        routing identity matrices: not learned, used to convert top-k indices generated by the router into one-hot vectors for routing.
        """
        replicate_mapper = (
            ttnn.ReplicateTensorToMesh(self.device) if self.is_mesh else None
        )
        router_w = self.hf_moe.router.layer.weight.to(torch.bfloat16).T.contiguous()
        self.router_weight_tt = ttnn.from_torch(
            router_w,
            device=self.device,
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            memory_config=ttnn.DRAM_MEMORY_CONFIG,
            mesh_mapper=replicate_mapper,
        )
        self._load_routing_matrices(replicate_mapper)

    def _load_routing_matrices(self, replicate_mapper):
        """Upload identity matrices."""
        E = self.num_experts
        eye = torch.eye(E, dtype=torch.bfloat16)

        if self._is_multirow:
            # This matrix is used to convert top-k indices to one-hot vectors for each device.
            # For example, if the top-k indices are [0, 2, 5] and the number of experts is 8, the one-hot vectors would be:
            # [[1, 0, 0, 0, 0, 0, 0, 0],
            #  [0, 0, 1, 0, 0, 0, 0, 0],
            #  [0, 0, 0, 0, 0, 1, 0, 0]]
            self._routing_eye_tt = ttnn.from_torch(
                eye,
                device=self.device,
                dtype=ttnn.bfloat16,
                layout=ttnn.ROW_MAJOR_LAYOUT,
                memory_config=ttnn.DRAM_MEMORY_CONFIG,
                mesh_mapper=self._ep_mapper,
            )
            self._routing_proj_tt = None
        else:
            self._routing_eye_tt = ttnn.from_torch(
                eye,
                device=self.device,
                dtype=ttnn.bfloat16,
                layout=ttnn.ROW_MAJOR_LAYOUT,
                memory_config=ttnn.DRAM_MEMORY_CONFIG,
                mesh_mapper=replicate_mapper,
            )
            # For column-parallel expert parallelism,
            # we need a projection matrix to map the one-hot vectors to the local experts on each device.
            # For example, if the top-k indices are [0, 2, 5] and the number of experts is 8, and we have 4 devices with 2 experts each, the projection matrix would be:
            # [[1, 0, 0, 0],
            #  [0, 0, 1, 0],
            #  [0, 0, 0, 0],
            #  [0, 0, 0, 0],
            #  [0, 0, 0, 0],
            #  [0, 0, 0, 1],
            #  [0, 0, 0, 0],
            #  [0, 0, 0, 0]]
            # The index is 2, it will be mapped to the local expert 1 on device 1, and the index is 5, it will be mapped to the local expert 1 on device 2.
            # because the local experts on each device are [0, 1] for device 0, [2, 3] for device 1, [4, 5] for device 2, and [6, 7] for device 3.
            self._routing_proj_tt = ttnn.from_torch(
                eye,
                device=self.device,
                dtype=ttnn.bfloat16,
                layout=ttnn.TILE_LAYOUT,
                memory_config=ttnn.DRAM_MEMORY_CONFIG,
                mesh_mapper=self._ep_mapper,
            )

    def _load_weights(self):
        """Upload MoE weights to device."""
        W_in_4d = (
            self.hf_moe.input_linear.weight.to(torch.bfloat16)
            .transpose(1, 2)
            .contiguous()
            .unsqueeze(0)
        )
        W_out_4d = (
            self.hf_moe.output_linear.weight.to(torch.bfloat16)
            .transpose(1, 2)
            .contiguous()
            .unsqueeze(0)
        )

        # Determine if we can use direct upload (no typecast) based on the weight size and dtype.
        # + If the weight is small enough, we can use direct upload to avoid the overhead of typecasting on the device.
        # + If the weight is large, we can use typecasting to save memory and bandwidth.
        _per_dev_bytes_bf16 = W_in_4d.numel() * 2 // max(self.effective_devs, 1)
        _use_direct = (
            self.dtype != ttnn.bfloat16 and _per_dev_bytes_bf16 > 100 * 1024 * 1024
        )

        print(
            f"  [moe_tt] uploading gate_up shape={list(W_in_4d.shape)} dtype={self.dtype} direct={_use_direct}",
            flush=True,
        )
        self.gate_up_proj = ttnn.from_torch(
            W_in_4d,
            device=self.device,
            dtype=self.dtype if _use_direct else ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            memory_config=ttnn.DRAM_MEMORY_CONFIG,
            mesh_mapper=self._ep_mapper,
        )
        if not _use_direct and self.dtype != ttnn.bfloat16:
            tmp = self.gate_up_proj
            self.gate_up_proj = ttnn.typecast(
                tmp, self.dtype, memory_config=ttnn.DRAM_MEMORY_CONFIG
            )
            tmp.deallocate(True)

        print(
            f"  [moe_tt] uploading down_proj shape={list(W_out_4d.shape)}", flush=True
        )
        self.down_proj = ttnn.from_torch(
            W_out_4d,
            device=self.device,
            dtype=self.dtype if _use_direct else ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            memory_config=ttnn.DRAM_MEMORY_CONFIG,
            mesh_mapper=self._ep_mapper,
        )
        if not _use_direct and self.dtype != ttnn.bfloat16:
            tmp = self.down_proj
            self.down_proj = ttnn.typecast(
                tmp, self.dtype, memory_config=ttnn.DRAM_MEMORY_CONFIG
            )
            tmp.deallocate(True)
        print(f"  [moe_tt] weights loaded", flush=True)

    def compute_routing_cpu(self, hidden_states_tt):
        """Compute routing weights on CPU."""
        E = self.num_experts
        S = hidden_states_tt.shape[2]
        logits_tt = ttnn.linear(
            hidden_states_tt,
            self.router_weight_tt,
            dtype=ttnn.bfloat16,
            memory_config=ttnn.DRAM_MEMORY_CONFIG,
        )
        if self.is_mesh:
            logits_cpu = ttnn.to_torch(
                logits_tt, mesh_composer=ttnn.ConcatMeshToTensor(self.device, dim=0)
            )[0:1]
        else:
            logits_cpu = logits_tt.cpu().to_torch()
        logits_tt.deallocate(True)
        return self._routing_from_logits(logits_cpu.reshape(-1, E)[:S], S)

    def _routing_from_logits(self, logits_SE, S):
        """Convert logits to routing weights."""
        E = self.num_experts
        top_k_logits, top_k_indices = logits_SE.topk(self.top_k, dim=1)
        top_k_weights = torch.softmax(top_k_logits.float(), dim=1).to(torch.bfloat16)
        routing_SE = torch.zeros(S, E, dtype=torch.bfloat16)
        routing_SE.scatter_add_(1, top_k_indices, top_k_weights)
        routing_4d = routing_SE.T.unsqueeze(-1).unsqueeze(0)
        return ttnn.from_torch(
            routing_4d,
            device=self.device,
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            memory_config=ttnn.DRAM_MEMORY_CONFIG,
            mesh_mapper=self._ep_mapper,
        )

    def compute_routing_device(self, hidden_states_tt):
        """
        Compute routing weights on device (TTNN) for single-token decode.
        """
        E_local = self.experts_per_device
        L1 = ttnn.L1_MEMORY_CONFIG

        # Step 1: score each expert
        logits_tt = ttnn.linear(
            hidden_states_tt,
            self.router_weight_tt,
            dtype=ttnn.bfloat16,
            memory_config=L1,
        )

        # Step 2: pick top_k experts by score
        vals_tt, idxs_tt = ttnn.topk(logits_tt, k=self.top_k, dim=3)
        logits_tt.deallocate(True)

        # Step 3: normalize top_k scores to routing weights
        weights_tt = ttnn.softmax(vals_tt, dim=3, memory_config=L1)
        vals_tt.deallocate(True)

        # Step 4: convert top_k indices to one-hot vectors via identity matrix lookup.
        idxs_u32 = ttnn.typecast(idxs_tt, ttnn.uint32)
        idxs_tt.deallocate(True)

        idxs_2d = ttnn.reshape(idxs_u32, [1, self.top_k])
        idxs_u32.deallocate(True)

        onehot_tt = ttnn.embedding(
            idxs_2d,
            self._routing_eye_tt,
            layout=ttnn.TILE_LAYOUT,
            memory_config=L1,
        )
        idxs_2d.deallocate(True)

        # Step 5: scale each one-hot by its routing weight
        weights_3d = ttnn.reshape(weights_tt, [1, self.top_k, 1])
        weights_tt.deallocate(True)

        scaled_tt = ttnn.mul(onehot_tt, weights_3d, memory_config=L1)
        onehot_tt.deallocate(True)
        weights_3d.deallocate(True)

        # Step 6: sum the scaled one-hots to get the final routing weights
        if self._is_multirow:
            routing_local = ttnn.sum(scaled_tt, dim=1, keepdim=False, memory_config=L1)
            scaled_tt.deallocate(True)
            routing_tt = ttnn.reshape(routing_local, [1, E_local, 1, 1])
            routing_local.deallocate(True)
        else:
            E = self.num_experts
            scaled_4d = ttnn.reshape(scaled_tt, [1, 1, self.top_k, E])
            scaled_tt.deallocate(True)
            routing_4d = ttnn.sum(scaled_4d, dim=2, keepdim=True, memory_config=L1)
            scaled_4d.deallocate(True)

            routing_local = ttnn.linear(
                routing_4d,
                self._routing_proj_tt,
                dtype=ttnn.bfloat16,
                memory_config=L1,
            )
            routing_4d.deallocate(True)
            routing_tt = ttnn.reshape(routing_local, [1, E_local, 1, 1])
            routing_local.deallocate(True)

        return routing_tt

    def _all_gather_col(self, x, dim, memory_config):
        """All-gather along column axis (cluster_axis=1)"""
        if self.tt_ccl is not None:
            return ttnn.experimental.all_gather_async(
                x,
                persistent_output_buffer=None,
                dim=dim,
                cluster_axis=1,
                multi_device_global_semaphore=self.tt_ccl.get_and_cycle_ag_semaphore_handles(
                    1
                ),
                barrier_semaphore=self.tt_ccl.get_and_cycle_barrier_semaphore_handle(1),
                num_links=self.tt_ccl.get_num_links(1),
                memory_config=memory_config,
                topology=self._topology,
                chunks_per_sync=1,
                num_workers_per_link=1,
                num_buffers_per_channel=2,
            )
        return ttnn.all_gather(x, dim=dim, cluster_axis=1, memory_config=memory_config)

    def _all_gather_row(self, x, dim, memory_config):
        """All-gather along row axis (cluster_axis=0)"""
        if self.tt_ccl is not None:
            return ttnn.experimental.all_gather_async(
                x,
                persistent_output_buffer=None,
                dim=dim,
                cluster_axis=0,
                multi_device_global_semaphore=self.tt_ccl.get_and_cycle_ag_semaphore_handles(
                    0
                ),
                barrier_semaphore=self.tt_ccl.get_and_cycle_barrier_semaphore_handle(0),
                num_links=self.tt_ccl.get_num_links(0),
                memory_config=memory_config,
                topology=self._topology,
                chunks_per_sync=1,
                num_workers_per_link=1,
                num_buffers_per_channel=2,
            )
        return ttnn.all_gather(x, dim=dim, cluster_axis=0, memory_config=memory_config)

    def forward(self, hidden_states_tt, routing_tt=None):
        I = self.intermediate_size
        E_local = self.experts_per_device
        S = hidden_states_tt.shape[2]
        MC = ttnn.DRAM_MEMORY_CONFIG

        if routing_tt is None:
            routing_tt = getattr(self, "_precomputed_routing", None)
        self._precomputed_routing = None
        if routing_tt is None:
            if S == 1 and (self._use_col_parallel or self._is_multirow):
                routing_tt = self.compute_routing_device(hidden_states_tt)
            else:
                routing_tt = self.compute_routing_cpu(hidden_states_tt)

        hidden_exp = ttnn.repeat(
            hidden_states_tt,
            ttnn.Shape([1, E_local, 1, 1]),
            memory_config=MC,
        )
        gate_up_out = ttnn.matmul(
            hidden_exp, self.gate_up_proj, dtype=self.act_dtype, memory_config=MC
        )
        hidden_exp.deallocate(True)

        gate_tt = gate_up_out[:, :, :, :I]
        up_tt = gate_up_out[:, :, :, I:]
        gate_up_out.deallocate(True)

        activated_tt = ttnn.mul(
            ttnn.silu(gate_tt, memory_config=MC), up_tt, memory_config=MC
        )
        gate_tt.deallocate(True)
        up_tt.deallocate(True)

        expert_out_tt = ttnn.matmul(
            activated_tt, self.down_proj, dtype=self.act_dtype, memory_config=MC
        )
        activated_tt.deallocate(True)

        weighted_tt = ttnn.mul(expert_out_tt, routing_tt, memory_config=MC)
        expert_out_tt.deallocate(True)
        routing_tt.deallocate(True)

        local_sum_tt = ttnn.sum(weighted_tt, dim=1, keepdim=True, memory_config=MC)
        weighted_tt.deallocate(True)

        if self._use_col_parallel and self.effective_cols > 1:
            gathered_tt = self._all_gather_col(local_sum_tt, dim=1, memory_config=MC)
            local_sum_tt.deallocate(True)
            result_tt = ttnn.sum(gathered_tt, dim=1, keepdim=True, memory_config=MC)
            gathered_tt.deallocate(True)
        elif self._is_multirow and self.effective_devs > 1:
            gathered_tt = self._all_gather_row(local_sum_tt, dim=1, memory_config=MC)
            local_sum_tt.deallocate(True)
            result_tt = ttnn.sum(gathered_tt, dim=1, keepdim=True, memory_config=MC)
            gathered_tt.deallocate(True)
        else:
            result_tt = local_sum_tt

        return result_tt
